import * as cdk from 'aws-cdk-lib';
import { AwsCostIntelligenceBotStack } from '../lib/aws-cost-intelligence-bot-stack';
import { Match, Template } from 'aws-cdk-lib/assertions';

// Creates a synthesized template used to validate the infrastructure configuration.
const app = new cdk.App();
const stack = new AwsCostIntelligenceBotStack(app, 'TestStack');
const template = Template.fromStack(stack);

// Verifies that the application deploys exactly one Lambda function.
test('creates one Lambda function', () => {
  template.resourceCountIs('AWS::Lambda::Function', 1);
});

// Verifies the Lambda uses the expected runtime and resource configuration.
test('configures Lambda correctly', () => {
  template.hasResourceProperties('AWS::Lambda::Function', {
    Runtime: 'nodejs22.x',
    Handler: 'index.handler',
    MemorySize: 256,
    Timeout: 30,
  });
});

// Verifies that CloudWatch logs are automatically expired after seven days.
test('configures seven day log retention', () => {
  template.hasResourceProperties('AWS::Logs::LogGroup', {
    RetentionInDays: 7,
  });
});

// Verifies the Lambda can retrieve cost and usage data from Cost Explorer.
test('grants Cost Explorer read permission', () => {
  template.hasResourceProperties('AWS::IAM::Policy', {
    PolicyDocument: {
      Statement: Match.arrayWith([
        Match.objectLike({
          Action: 'ce:GetCostAndUsage',
          Effect: 'Allow',
          Resource: '*',
        }),
      ]),
    },
  });
});

// Verifies the Lambda can read only the two expected Telegram parameters.
test('grants restricted Telegram SSM read permission', () => {
  // Retrieves the IAM policies generated by CDK.
  const policies = template.findResources('AWS::IAM::Policy');

  // Collects the policy statements that grant SSM parameter access.
  const ssmStatements = Object.values(policies)
    .flatMap((policy: any) => policy.Properties.PolicyDocument.Statement)
    .filter((statement: any) => statement.Action === 'ssm:GetParameter');

  // Ensures exactly one SSM permission statement exists.
  expect(ssmStatements).toHaveLength(1);

  // Ensures the permission allows only the two expected parameter ARNs.
  expect(ssmStatements[0].Effect).toBe('Allow');

  const resources = ssmStatements[0].Resource;

  expect(Array.isArray(resources)).toBe(true);
  expect(resources).toHaveLength(2);
  expect(resources).not.toContain('*');

  // Verifies the exact allowed parameter paths.
  const resourceStrings = resources.map((resource: unknown) =>
    JSON.stringify(resource),
  );

  expect(resourceStrings.filter((resource: string) =>
    resource.includes('cloudrizz/cost-bot/telegram/token'),
  )).toHaveLength(1);

  expect(resourceStrings.filter((resource: string) =>
    resource.includes('cloudrizz/cost-bot/telegram/chat-id'),
  )).toHaveLength(1);
});

// Verifies the Lambda is limited to one concurrent execution.
test('limits Lambda concurrency to one', () => {
  template.hasResourceProperties('AWS::Lambda::Function', {
    ReservedConcurrentExecutions: 1,
  });
});

// Verifies the dead-letter queue has seven-day retention and SQS-managed encryption.
test('configures an encrypted SQS dead-letter queue', () => {
  template.resourceCountIs('AWS::SQS::Queue', 1);

  template.hasResourceProperties('AWS::SQS::Queue', {
    MessageRetentionPeriod: 604800,
    SqsManagedSseEnabled: true,
  });
});

// Verifies the Lambda sends failed asynchronous invocations to the dead-letter queue.
test('connects the dead-letter queue to Lambda', () => {
  template.hasResourceProperties('AWS::Lambda::Function', {
    DeadLetterConfig: {
      TargetArn: {
        'Fn::GetAtt': [
          Match.anyValue(),
          'Arn',
        ],
      },
    },
  });
});

// Verifies the Lambda can send failed events only to its SQS dead-letter queue.
test('restricts SQS SendMessage permission to the dead-letter queue', () => {
  // Retrieves the IAM policies generated by CDK.
  const policies = template.findResources('AWS::IAM::Policy');

  // Finds statements that grant SQS SendMessage.
  const sqsStatements = Object.values(policies)
    .flatMap((policy: any) => policy.Properties.PolicyDocument.Statement)
    .filter((statement: any) => statement.Action === 'sqs:SendMessage');

  // Ensures exactly one SQS SendMessage permission exists.
  expect(sqsStatements).toHaveLength(1);

  // Ensures the permission is allowed only for our DLQ.
  expect(sqsStatements[0].Effect).toBe('Allow');

  const queues = template.findResources('AWS::SQS::Queue');
  const dlqLogicalId = Object.keys(queues)[0];

  expect(sqsStatements[0].Resource).toEqual({
    'Fn::GetAtt': [dlqLogicalId, 'Arn'],
  });
});

// Verifies that exactly two CloudWatch alarms are created.
test('creates two CloudWatch alarms', () => {
  template.resourceCountIs('AWS::CloudWatch::Alarm', 2);
});

// Verifies that both alarms monitor the expected metrics and failure thresholds.
test('configures CloudWatch alarm thresholds correctly', () => {
  const alarms = template.findResources('AWS::CloudWatch::Alarm');

  // Confirms both alarms use the expected monitoring configuration.
  for (const alarm of Object.values(alarms) as any[]) {
    expect(alarm.Properties.Threshold).toBe(1);
    expect(alarm.Properties.EvaluationPeriods).toBe(1);
    expect(alarm.Properties.TreatMissingData).toBe('notBreaching');
    expect(alarm.Properties.Period).toBe(300);
  }

  // Confirms we monitor Lambda errors and failed SQS messages.
  const metrics = Object.values(alarms).map(
    (alarm: any) => alarm.Properties.MetricName,
  );

  expect(metrics).toContain('Errors');
  expect(metrics).toContain('ApproximateNumberOfMessagesVisible');
});
